//! Project scaffolding for `temper init`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};


/// Minimal CSDL template for a new project.
const CSDL_TEMPLATE: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="{{namespace}}" xmlns="http://docs.oasis-open.org/odata/ns/edm">

      <!-- Define your entity types here -->
      <EntityType Name="Example">
        <Key>
          <PropertyRef Name="Id"/>
        </Key>
        <Property Name="Id" Type="Edm.Guid" Nullable="false"/>
        <Property Name="Name" Type="Edm.String" Nullable="false"/>
        <Property Name="CreatedAt" Type="Edm.DateTimeOffset" Nullable="false"/>
      </EntityType>

      <EntityContainer Name="Service">
        <EntitySet Name="Examples" EntityType="{{namespace}}.Example"/>
      </EntityContainer>

    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
"#;

/// Template Cargo.toml for the generated project.
const CARGO_TEMPLATE: &str = r#"[package]
name = "{{name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
temper-runtime = { path = "../../crates/temper-runtime" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
"#;

/// Run the `temper init <name>` command.
///
/// Creates the full project directory structure under the given name.
pub fn run(name: &str) -> Result<()> {
    let root = Path::new(name);

    if root.exists() {
        anyhow::bail!("Directory '{}' already exists", name);
    }

    println!("Initializing Temper project '{name}'...");

    // Create the directory tree
    let dirs = [
        root.join("specs").join("policies"),
        root.join("generated"),
        root.join("evolution").join("observations"),
        root.join("evolution").join("problems"),
        root.join("evolution").join("analyses"),
        root.join("evolution").join("decisions"),
        root.join("evolution").join("insights"),
        root.join("src"),
    ];

    for dir in &dirs {
        fs::create_dir_all(dir)
            .with_context(|| format!("Failed to create directory: {}", dir.display()))?;
        println!("  Created {}", dir.display());
    }

    // Derive a PascalCase namespace from the project name
    let namespace = to_namespace(name);

    // Write the CSDL template
    let csdl_path = root.join("specs").join("model.csdl.xml");
    let csdl_content = CSDL_TEMPLATE.replace("{{namespace}}", &namespace);
    fs::write(&csdl_path, csdl_content)
        .with_context(|| format!("Failed to write {}", csdl_path.display()))?;
    println!("  Wrote {}", csdl_path.display());

    // Write the Cargo.toml
    let cargo_path = root.join("Cargo.toml");
    let cargo_content = CARGO_TEMPLATE.replace("{{name}}", name);
    fs::write(&cargo_path, cargo_content)
        .with_context(|| format!("Failed to write {}", cargo_path.display()))?;
    println!("  Wrote {}", cargo_path.display());

    // Write a minimal main.rs
    let main_path = root.join("src").join("main.rs");
    let main_content = format!(
        "//! {} — generated by `temper init`.\n\nfn main() {{\n    println!(\"Hello from {}!\");\n}}\n",
        name, name
    );
    fs::write(&main_path, main_content)
        .with_context(|| format!("Failed to write {}", main_path.display()))?;
    println!("  Wrote {}", main_path.display());

    println!("\nProject '{}' initialized successfully!", name);
    println!("Next steps:");
    println!("  1. Edit specs/model.csdl.xml to define your entity model");
    println!("  2. Add TLA+ specs in the specs/ directory");
    println!("  3. Run `temper codegen` to generate Rust code");

    Ok(())
}

/// Convert a kebab-case or snake_case project name into a PascalCase namespace.
///
/// Examples: "my-app" -> "Temper.MyApp", "hello_world" -> "Temper.HelloWorld"
fn to_namespace(name: &str) -> String {
    let pascal: String = name
        .split(|c: char| c == '-' || c == '_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    format!("{}{}", upper, chars.collect::<String>())
                }
                None => String::new(),
            }
        })
        .collect();

    format!("Temper.{}", pascal)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_namespace() {
        assert_eq!(to_namespace("my-app"), "Temper.MyApp");
        assert_eq!(to_namespace("hello_world"), "Temper.HelloWorld");
        assert_eq!(to_namespace("simple"), "Temper.Simple");
    }

    #[test]
    fn test_init_creates_directory_structure() {
        let project_dir = std::env::temp_dir().join(format!(
            "temper_test_init_project_{}",
            std::process::id()
        ));
        // Clean up in case of previous failed run
        let _ = fs::remove_dir_all(&project_dir);

        // Pass the full absolute path as the project name so we don't need chdir
        let project_path_str = project_dir.to_str().unwrap().to_string();
        let result = run(&project_path_str);
        result.expect("init should succeed");

        // Verify directory structure
        assert!(project_dir.join("specs").is_dir());
        assert!(project_dir.join("specs/policies").is_dir());
        assert!(project_dir.join("specs/model.csdl.xml").is_file());
        assert!(project_dir.join("generated").is_dir());
        assert!(project_dir.join("evolution/observations").is_dir());
        assert!(project_dir.join("evolution/problems").is_dir());
        assert!(project_dir.join("evolution/analyses").is_dir());
        assert!(project_dir.join("evolution/decisions").is_dir());
        assert!(project_dir.join("evolution/insights").is_dir());
        assert!(project_dir.join("Cargo.toml").is_file());
        assert!(project_dir.join("src/main.rs").is_file());

        // Verify CSDL content contains a namespace
        let csdl = fs::read_to_string(project_dir.join("specs/model.csdl.xml")).unwrap();
        assert!(
            csdl.contains("Namespace=\"Temper."),
            "CSDL should contain a Temper namespace"
        );

        // Verify Cargo.toml content contains the project name
        let cargo = fs::read_to_string(project_dir.join("Cargo.toml")).unwrap();
        assert!(
            cargo.contains(&project_path_str),
            "Cargo.toml should contain the project name"
        );

        // Clean up
        let _ = fs::remove_dir_all(&project_dir);
    }

    #[test]
    fn test_init_fails_if_directory_exists() {
        let project_dir = std::env::temp_dir().join(format!(
            "temper_test_init_exists_{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&project_dir);
        fs::create_dir_all(&project_dir).unwrap();

        let project_path_str = project_dir.to_str().unwrap().to_string();
        let result = run(&project_path_str);

        assert!(result.is_err());
        assert!(
            result.unwrap_err().to_string().contains("already exists"),
            "error should mention directory already exists"
        );

        let _ = fs::remove_dir_all(&project_dir);
    }
}
