ALTER TABLE tenant_installed_apps
    ADD COLUMN IF NOT EXISTS source_kind TEXT NOT NULL DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS app_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS version_hash TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS closure_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS registry_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS registry_tenant TEXT NOT NULL DEFAULT '';
