#!/bin/bash
# Readability Ratchet
#
# Prevents readability regressions by enforcing non-increasing "debt" metrics.
# Usage:
#   bash scripts/readability-ratchet.sh snapshot [.ci/readability-baseline.env]
#   bash scripts/readability-ratchet.sh check [.ci/readability-baseline.env]
#   bash scripts/readability-ratchet.sh show
set -euo pipefail

WORKSPACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-check}"
BASELINE_INPUT="${2:-.ci/readability-baseline.env}"

if [[ "$BASELINE_INPUT" = /* ]]; then
    BASELINE_PATH="$BASELINE_INPUT"
else
    BASELINE_PATH="$WORKSPACE_ROOT/$BASELINE_INPUT"
fi

TMP_METRICS="$(mktemp)"

cleanup() {
    rm -f "$TMP_METRICS"
}
trap cleanup EXIT

is_production_file() {
    local file="$1"
    case "$file" in
        */tests/*|*/benches/*|*test_*.rs|*_test.rs|*/temper-macros/*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

metric_value() {
    local file="$1"
    local key="$2"
    grep -E "^${key}=" "$file" | head -1 | cut -d= -f2- || true
}

collect_metrics() {
    local prod_total=0
    local prod_gt300=0
    local prod_gt500=0
    local prod_gt1000=0
    local prod_max_lines=0
    local prod_max_path=""
    local prod_println_count=0
    local prod_unwrap_ci_ok_count=0

    while IFS= read -r -d '' file; do
        if ! is_production_file "$file"; then
            continue
        fi

        prod_total=$((prod_total + 1))

        local lines
        lines="$(wc -l < "$file" | tr -d '[:space:]')"

        if (( lines > 300 )); then prod_gt300=$((prod_gt300 + 1)); fi
        if (( lines > 500 )); then prod_gt500=$((prod_gt500 + 1)); fi
        if (( lines > 1000 )); then prod_gt1000=$((prod_gt1000 + 1)); fi

        if (( lines > prod_max_lines )); then
            prod_max_lines="$lines"
            prod_max_path="${file#$WORKSPACE_ROOT/}"
        fi

        local pcount
        pcount="$(
            grep -nE '(^|[^[:alnum:]_])e?println!\(' "$file" 2>/dev/null \
                | cut -d: -f2- \
                | grep -vc '^[[:space:]]*//' || true
        )"
        prod_println_count=$((prod_println_count + pcount))

        local ucount
        ucount="$(
            grep -n '\.unwrap()' "$file" 2>/dev/null \
                | grep -c '// ci-ok' || true
        )"
        prod_unwrap_ci_ok_count=$((prod_unwrap_ci_ok_count + ucount))
    done < <(find "$WORKSPACE_ROOT/crates" -type f -name '*.rs' -print0)

    local allow_clippy_count
    local allow_dead_code_count
    allow_clippy_count="$(
        (grep -R --include='*.rs' -nE '#\[allow\(clippy::' "$WORKSPACE_ROOT/crates" || true) \
            | wc -l | tr -d '[:space:]'
    )"
    allow_dead_code_count="$(
        (grep -R --include='*.rs' -nE '#\[allow\(dead_code\)\]' "$WORKSPACE_ROOT/crates" || true) \
            | wc -l | tr -d '[:space:]'
    )"

    cat <<EOF
# Generated by scripts/readability-ratchet.sh
PROD_RS_TOTAL=$prod_total
PROD_FILES_GT300=$prod_gt300
PROD_FILES_GT500=$prod_gt500
PROD_FILES_GT1000=$prod_gt1000
PROD_MAX_FILE_LINES=$prod_max_lines
PROD_MAX_FILE_PATH=$prod_max_path
ALLOW_CLIPPY_COUNT=$allow_clippy_count
ALLOW_DEAD_CODE_COUNT=$allow_dead_code_count
PROD_PRINTLN_COUNT=$prod_println_count
PROD_UNWRAP_CI_OK_COUNT=$prod_unwrap_ci_ok_count
EOF
}

print_metrics() {
    local file="$1"
    echo "Readability metrics:"
    grep -v '^#' "$file" | sed '/^$/d'
}

compare_non_increasing() {
    local baseline_file="$1"
    local current_file="$2"

    local failed=false
    local blocking_keys=(
        "PROD_FILES_GT300"
        "PROD_FILES_GT500"
        "PROD_FILES_GT1000"
        "PROD_MAX_FILE_LINES"
        "ALLOW_CLIPPY_COUNT"
        "ALLOW_DEAD_CODE_COUNT"
        "PROD_PRINTLN_COUNT"
        "PROD_UNWRAP_CI_OK_COUNT"
    )
    local advisory_keys=(
        "PROD_FILES_GT300"
    )

    echo "Readability ratchet check (blocking: current <= baseline):"
    for key in "${blocking_keys[@]}"; do
        # Skip advisory-only keys in blocking loop.
        if [[ "$key" = "PROD_FILES_GT300" ]]; then
            continue
        fi

        local baseline_val
        local current_val
        baseline_val="$(metric_value "$baseline_file" "$key")"
        current_val="$(metric_value "$current_file" "$key")"

        if [[ -z "$baseline_val" || -z "$current_val" ]]; then
            echo "  FAIL $key missing in baseline or current metrics"
            failed=true
            continue
        fi

        if (( current_val > baseline_val )); then
            echo "  FAIL $key: baseline=$baseline_val current=$current_val"
            failed=true
        else
            echo "  OK   $key: baseline=$baseline_val current=$current_val"
        fi
    done

    echo "Readability advisory metrics (tracked, non-blocking):"
    for key in "${advisory_keys[@]}"; do
        local baseline_val
        local current_val
        baseline_val="$(metric_value "$baseline_file" "$key")"
        current_val="$(metric_value "$current_file" "$key")"

        if [[ -z "$baseline_val" || -z "$current_val" ]]; then
            echo "  WARN $key missing in baseline or current metrics"
            continue
        fi

        if (( current_val > baseline_val )); then
            echo "  WARN $key: baseline=$baseline_val current=$current_val"
        else
            echo "  OK   $key: baseline=$baseline_val current=$current_val"
        fi
    done

    if [[ "$failed" = true ]]; then
        echo ""
        echo "Readability regression detected."
        echo "Reduce the regressions or intentionally update baseline with:"
        echo "  bash scripts/readability-ratchet.sh snapshot .ci/readability-baseline.env"
        exit 1
    fi
}

case "$MODE" in
    snapshot)
        mkdir -p "$(dirname "$BASELINE_PATH")"
        collect_metrics > "$BASELINE_PATH"
        echo "Wrote baseline: $BASELINE_PATH"
        print_metrics "$BASELINE_PATH"
        ;;
    show)
        collect_metrics > "$TMP_METRICS"
        print_metrics "$TMP_METRICS"
        ;;
    check)
        if [[ ! -f "$BASELINE_PATH" ]]; then
            echo "Missing baseline file: $BASELINE_PATH"
            echo "Create one with:"
            echo "  bash scripts/readability-ratchet.sh snapshot .ci/readability-baseline.env"
            exit 1
        fi
        collect_metrics > "$TMP_METRICS"
        compare_non_increasing "$BASELINE_PATH" "$TMP_METRICS"
        echo ""
        print_metrics "$TMP_METRICS"
        ;;
    *)
        echo "Unknown mode: $MODE"
        echo "Usage:"
        echo "  bash scripts/readability-ratchet.sh snapshot [.ci/readability-baseline.env]"
        echo "  bash scripts/readability-ratchet.sh check [.ci/readability-baseline.env]"
        echo "  bash scripts/readability-ratchet.sh show"
        exit 2
        ;;
esac
