//! Deterministic, capability-scoped Rust client generation for WASM modules.

use std::collections::BTreeSet;

use temper_spec::csdl::{Action, CsdlDocument, EntityType};
use temper_wasm_sdk::data::{
    ArtifactModuleSdkBinding, EntityDataGrant, ManifestActionV1, ManifestEntityV1,
    ManifestPropertyV1, ModuleDataGrant, ModuleSdkManifest, ModuleSdkMetadataDigests,
    bind_module_sdk_artifact,
};

mod names;
mod schema_helpers;
mod source_types;
mod types;
use names::{reject_generated_collisions, rust_field_name, rust_type_name};
use schema_helpers::{entity_sets, enum_members};
use source_types::{
    emit_artifact_binding, emit_named_property_type, emit_query_types, generated_rust_type,
    generated_type_name, hex_sha256,
};
pub use types::{GeneratedModuleSdk, PackagedModuleSdk};

/// A fail-closed schema or naming error during module SDK generation.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum ModuleSdkCodegenError {
    #[error("invalid module data grant: {0}")]
    InvalidGrant(String),
    #[error("granted entity type '{0}' is absent from the verified CSDL closure")]
    MissingEntity(String),
    #[error("entity type '{0}' has no entity set in the verified CSDL closure")]
    MissingEntitySet(String),
    #[error("granted schema symbol '{symbol}' is absent from entity '{entity_type}'")]
    MissingSymbol { entity_type: String, symbol: String },
    #[error("generated Rust identifier collision '{0}'")]
    IdentifierCollision(String),
    #[error("failed to construct module SDK manifest: {0}")]
    Manifest(String),
    #[error("failed to bind compiled module artifact: {0}")]
    ArtifactBinding(String),
}

/// Bind generated metadata into compiled WebAssembly and finalize its digest.
///
/// Build tooling calls this after compiling [`GeneratedModuleSdk::source`] and
/// before constructing the published application bundle.
pub fn package_generated_module_sdk(
    wasm: &[u8],
    mut generated: GeneratedModuleSdk,
) -> Result<PackagedModuleSdk, ModuleSdkCodegenError> {
    let binding = ArtifactModuleSdkBinding::from_manifest(&generated.manifest)
        .map_err(ModuleSdkCodegenError::ArtifactBinding)?;
    let wasm =
        bind_module_sdk_artifact(wasm, &binding).map_err(ModuleSdkCodegenError::ArtifactBinding)?;
    generated.manifest.artifact_digest = hex_sha256(&wasm);
    Ok(PackagedModuleSdk {
        wasm,
        manifest: generated.manifest,
    })
}

/// Generate a module-specific Rust client from a verified closure and exact grant.
pub fn generate_module_sdk(
    csdl: &CsdlDocument,
    module_name: &str,
    closure_digest: &str,
    dependency_lock_digest: &str,
    artifact_digest: &str,
    grant: ModuleDataGrant,
) -> Result<GeneratedModuleSdk, ModuleSdkCodegenError> {
    grant
        .validate()
        .map_err(ModuleSdkCodegenError::InvalidGrant)?;
    let schema_bytes = serde_json::to_vec(csdl)
        .map_err(|error| ModuleSdkCodegenError::Manifest(error.to_string()))?;
    let schema_digest = hex_sha256(&schema_bytes);
    let entity_sets = entity_sets(csdl);
    let mut entities = Vec::new();
    let mut used_symbols = BTreeSet::new();
    let mut generated_names = BTreeSet::new();
    let mut generated_named_types = BTreeSet::new();
    let mut source = String::from(
        "// @generated by temper-codegen; do not edit.\nuse temper_wasm_sdk::data::*;\n\nfn invalid_generated_value(error: serde_json::Error) -> ModuleDataError { ModuleDataError::new(ModuleDataErrorKind::InvalidRequest, \"GeneratedValueEncodingFailed\", error.to_string(), Retryability::Never) }\n\n",
    );

    let mut entity_grants = grant.entities.iter().collect::<Vec<_>>();
    entity_grants.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    for entity_grant in entity_grants {
        let (entity, actions) = resolve_entity(csdl, entity_grant)?;
        let entity_set = entity_sets
            .get(entity_grant.entity_type.as_str())
            .ok_or_else(|| {
                ModuleSdkCodegenError::MissingEntitySet(entity_grant.entity_type.clone())
            })?;
        let generated = rust_type_name(&entity.name);
        if !generated_names.insert(generated.clone()) {
            return Err(ModuleSdkCodegenError::IdentifierCollision(generated));
        }
        used_symbols.insert(entity_grant.entity_type.clone());
        used_symbols.insert(entity_set.to_string());
        let properties = entity
            .properties
            .iter()
            .map(|property| ManifestPropertyV1 {
                canonical_name: property.name.clone(),
                generated_name: rust_field_name(&property.name),
                type_name: property.type_name.clone(),
                nullable: property.nullable,
                enum_members: enum_members(csdl, &property.type_name),
            })
            .collect::<Vec<_>>();
        for property in &properties {
            used_symbols.insert(format!(
                "property:{}:{}",
                entity_grant.entity_type, property.canonical_name
            ));
            used_symbols.insert(format!("type:{}", property.type_name));
            for member in &property.enum_members {
                used_symbols.insert(format!("enum:{}:{member}", property.type_name));
            }
        }
        reject_generated_collisions(
            &entity_grant.entity_type,
            properties
                .iter()
                .map(|property| (&property.canonical_name, &property.generated_name)),
        )?;
        let manifest_actions = actions
            .into_iter()
            .map(|action| {
                used_symbols.insert(action.name.clone());
                let manifest_action = ManifestActionV1 {
                    canonical_name: action.name.clone(),
                    generated_name: rust_field_name(&action.name),
                    parameters: action
                        .parameters
                        .iter()
                        .skip(1)
                        .map(|parameter| ManifestPropertyV1 {
                            canonical_name: parameter.name.clone(),
                            generated_name: rust_field_name(&parameter.name),
                            type_name: parameter.type_name.clone(),
                            nullable: parameter.nullable,
                            enum_members: enum_members(csdl, &parameter.type_name),
                        })
                        .collect(),
                    result_type: action
                        .return_type
                        .as_ref()
                        .map(|result| result.type_name.clone()),
                    result_enum_members: action
                        .return_type
                        .as_ref()
                        .map(|result| enum_members(csdl, &result.type_name))
                        .unwrap_or_default(),
                    composite: entity_grant.composite_actions.contains(&action.name),
                };
                for parameter in &manifest_action.parameters {
                    used_symbols.insert(format!(
                        "parameter:{}:{}:{}",
                        entity_grant.entity_type, action.name, parameter.canonical_name
                    ));
                    used_symbols.insert(format!("type:{}", parameter.type_name));
                    for member in &parameter.enum_members {
                        used_symbols.insert(format!("enum:{}:{member}", parameter.type_name));
                    }
                }
                if let Some(result_type) = &manifest_action.result_type {
                    used_symbols.insert(format!("result:{}:{}", action.name, result_type));
                    used_symbols.insert(format!("type:{result_type}"));
                    for member in &manifest_action.result_enum_members {
                        used_symbols.insert(format!("enum:{result_type}:{member}"));
                    }
                }
                manifest_action
            })
            .collect::<Vec<_>>();
        reject_generated_collisions(
            &entity_grant.entity_type,
            manifest_actions
                .iter()
                .map(|action| (&action.canonical_name, &action.generated_name)),
        )?;
        for property in &properties {
            emit_named_property_type(&mut source, property, &mut generated_named_types);
        }
        for action in &manifest_actions {
            for parameter in &action.parameters {
                emit_named_property_type(&mut source, parameter, &mut generated_named_types);
            }
            if let Some(type_name) = &action.result_type {
                emit_named_property_type(
                    &mut source,
                    &ManifestPropertyV1 {
                        canonical_name: "result".into(),
                        generated_name: "result".into(),
                        type_name: type_name.clone(),
                        nullable: false,
                        enum_members: action.result_enum_members.clone(),
                    },
                    &mut generated_named_types,
                );
            }
        }
        emit_entity_client(
            &mut source,
            &generated,
            &entity_grant.entity_type,
            &properties,
            &manifest_actions,
            &grant,
            entity_grant,
        );
        entities.push(ManifestEntityV1 {
            entity_type: entity_grant.entity_type.clone(),
            entity_set: entity_set.to_string(),
            generated_name: generated,
            properties,
            actions: manifest_actions,
        });
    }
    entities.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::Batch)
    {
        source.push_str("pub fn execute_batch(data: &mut DataClient, items: Vec<BatchItemV1>) -> Result<DataResultV1, ModuleDataError> { data.call(DataOperationV1::Batch { items }) }\n\n");
    }
    let manifest = ModuleSdkManifest::new(
        module_name,
        ModuleSdkMetadataDigests {
            closure: closure_digest.into(),
            dependency_lock: dependency_lock_digest.into(),
            schema: schema_digest,
        },
        artifact_digest,
        grant,
        entities,
        used_symbols,
    )
    .map_err(ModuleSdkCodegenError::Manifest)?;
    emit_artifact_binding(&mut source, &manifest);
    Ok(GeneratedModuleSdk { source, manifest })
}

fn resolve_entity<'a>(
    csdl: &'a CsdlDocument,
    grant: &EntityDataGrant,
) -> Result<(&'a EntityType, Vec<&'a Action>), ModuleSdkCodegenError> {
    let (namespace, name) = grant
        .entity_type
        .rsplit_once('.')
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let schema = csdl
        .schemas
        .iter()
        .find(|schema| schema.namespace == namespace)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let entity = schema
        .entity_type(name)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    if !grant.file_operations.is_empty() && (name != "File" || !entity.has_stream) {
        return Err(ModuleSdkCodegenError::MissingSymbol {
            entity_type: grant.entity_type.clone(),
            symbol: "File content capability on a HasStream File entity".into(),
        });
    }
    for field in grant
        .query_filter_fields
        .iter()
        .chain(&grant.query_order_fields)
    {
        if !entity
            .properties
            .iter()
            .any(|property| property.name == *field)
        {
            return Err(ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: field.clone(),
            });
        }
    }
    let mut actions = Vec::new();
    for name in grant.actions.iter().chain(&grant.composite_actions) {
        let action = schema
            .action(name)
            .ok_or_else(|| ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: name.clone(),
            })?;
        let bound_type = action
            .parameters
            .first()
            .map(|parameter| parameter.type_name.as_str());
        if !action.is_bound || bound_type != Some(grant.entity_type.as_str()) {
            return Err(ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: name.clone(),
            });
        }
        actions.push(action);
    }
    actions.sort_by(|left, right| left.name.cmp(&right.name));
    Ok((entity, actions))
}

fn emit_entity_client(
    source: &mut String,
    generated: &str,
    canonical: &str,
    properties: &[ManifestPropertyV1],
    actions: &[ManifestActionV1],
    grant: &ModuleDataGrant,
    entity_grant: &EntityDataGrant,
) {
    source.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]\n#[serde(transparent)]\npub struct {generated}Id(pub String);\n\n"
    ));
    source.push_str(&format!(
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {generated} {{\n"
    ));
    for property in properties {
        let rust_type = generated_rust_type(property);
        let rust_type = if property.nullable {
            format!("Option<{rust_type}>")
        } else {
            rust_type
        };
        source.push_str(&format!(
            "    #[serde(rename = \"{}\")]\n    pub {}: {},\n",
            property.canonical_name, property.generated_name, rust_type
        ));
    }
    source.push_str("}\n\n");
    source.push_str(&format!(
        "#[derive(Debug, Clone, serde::Serialize)]\npub struct {generated}Create {{\n"
    ));
    for property in properties {
        let rust_type = generated_rust_type(property);
        let rust_type = if property.nullable {
            format!("Option<{rust_type}>")
        } else {
            rust_type
        };
        source.push_str(&format!(
            "    #[serde(rename = \"{}\")]\n    pub {}: {},\n",
            property.canonical_name, property.generated_name, rust_type
        ));
    }
    source.push_str("}\n\n");
    source.push_str(&format!(
        "#[derive(Debug, Clone, Default, serde::Serialize)]\npub struct {generated}Patch {{\n"
    ));
    for property in properties {
        let rust_type = generated_rust_type(property);
        let rust_type = if property.nullable {
            format!("Option<Option<{rust_type}>>")
        } else {
            format!("Option<{rust_type}>")
        };
        source.push_str(&format!(
            "    #[serde(rename = \"{}\", skip_serializing_if = \"Option::is_none\")]\n    pub {}: {},\n",
            property.canonical_name,
            property.generated_name,
            rust_type
        ));
    }
    source.push_str("}\n\n");
    for action in actions {
        let operation_granted = if action.composite {
            grant
                .operations
                .contains(&temper_wasm_sdk::data::DataOperationKind::CompositeInvoke)
        } else {
            grant
                .operations
                .contains(&temper_wasm_sdk::data::DataOperationKind::ActionInvoke)
        };
        if !operation_granted {
            continue;
        }
        let action_type = format!(
            "{}{}Input",
            generated,
            rust_type_name(&action.canonical_name)
        );
        source.push_str(&format!(
            "#[derive(Debug, Clone, serde::Serialize)]\npub struct {action_type} {{\n"
        ));
        for parameter in &action.parameters {
            let rust_type = generated_rust_type(parameter);
            let rust_type = if parameter.nullable {
                format!("Option<{rust_type}>")
            } else {
                rust_type
            };
            source.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n    pub {}: {},\n",
                parameter.canonical_name, parameter.generated_name, rust_type
            ));
        }
        source.push_str("}\n\n");
    }
    emit_query_types(source, generated, properties, entity_grant);
    source.push_str(&format!(
        "pub struct {generated}Client {{ data: DataClient }}\nimpl {generated}Client {{\n    pub const ENTITY_TYPE: &'static str = \"{canonical}\";\n    pub fn new() -> Self {{ Self {{ data: DataClient::default() }} }}\n"
    ));
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::EntityGet)
    {
        source.push_str(&format!("    pub fn get(&mut self, id: impl Into<String>) -> Result<TypedEntity<{generated}>, ModuleDataError> {{ decode_entity(self.data.call(DataOperationV1::EntityGet {{ entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), at_least_sequence: None }})?) }}\n"));
    }
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::EntityQuery)
    {
        source.push_str(&format!("    pub fn query(&mut self, filter: Option<{generated}Filter>, order_by: Vec<{generated}Order>, page: PageV1) -> Result<TypedPage<{generated}>, ModuleDataError> {{ decode_page(self.data.call(DataOperationV1::EntityQuery {{ entity_type: Self::ENTITY_TYPE.into(), filter: filter.map(|value| value.0), order_by: order_by.into_iter().map(|value| value.0).collect(), page }})?) }}\n"));
    }
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::EntityCreate)
    {
        source.push_str(&format!("    pub fn create(&mut self, value: {generated}Create) -> Result<TypedWrite<{generated}>, ModuleDataError> {{ decode_write(self.data.call(DataOperationV1::EntityCreate {{ entity_type: Self::ENTITY_TYPE.into(), value: serde_json::to_value(value).map_err(invalid_generated_value)?.as_object().cloned().unwrap_or_default() }})?) }}\n"));
    }
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::EntityPatch)
    {
        source.push_str(&format!("    pub fn patch(&mut self, id: impl Into<String>, expected_sequence: Option<u64>, value: {generated}Patch) -> Result<TypedWrite<{generated}>, ModuleDataError> {{ decode_write(self.data.call(DataOperationV1::EntityPatch {{ entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), expected_sequence, value: serde_json::to_value(value).map_err(invalid_generated_value)?.as_object().cloned().unwrap_or_default() }})?) }}\n"));
    }
    for action in actions {
        let operation_granted = if action.composite {
            grant
                .operations
                .contains(&temper_wasm_sdk::data::DataOperationKind::CompositeInvoke)
        } else {
            grant
                .operations
                .contains(&temper_wasm_sdk::data::DataOperationKind::ActionInvoke)
        };
        if !operation_granted {
            continue;
        }
        let method = &action.generated_name;
        let action_type = format!(
            "{}{}Input",
            generated,
            rust_type_name(&action.canonical_name)
        );
        let operation = if action.composite {
            "CompositeInvoke"
        } else {
            "ActionInvoke"
        };
        let result_type = action.result_type.as_deref().map_or_else(
            || "serde_json::Value".to_string(),
            |type_name| generated_type_name(type_name, &action.result_enum_members),
        );
        source.push_str(&format!("    pub fn {method}(&mut self, id: impl Into<String>, expected_sequence: Option<u64>, params: {action_type}) -> Result<TypedAction<{result_type}>, ModuleDataError> {{ decode_action(self.data.call(DataOperationV1::{operation} {{ entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), action: \"{}\".into(), expected_sequence, params: serde_json::to_value(params).map_err(invalid_generated_value)?.as_object().cloned().unwrap_or_default() }})?) }}\n", action.canonical_name));
    }
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::FileRead)
        && (entity_grant
            .file_operations
            .contains(&temper_wasm_sdk::data::FileOperationKind::ContentRead)
            || entity_grant
                .file_operations
                .contains(&temper_wasm_sdk::data::FileOperationKind::VersionRead))
    {
        source.push_str("    pub fn open_file_read(&mut self, file_id: impl Into<String>, version_id: Option<String>) -> Result<OpenedFileRead, ModuleDataError> { decode_file_read(self.data.call(DataOperationV1::FileReadOpen { file_id: file_id.into(), version_id })?) }\n");
    }
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::FileWrite)
        && entity_grant
            .file_operations
            .contains(&temper_wasm_sdk::data::FileOperationKind::ContentWrite)
    {
        source.push_str("    pub fn open_file_write(&mut self, file_id: impl Into<String>, expected_sequence: Option<u64>, content_length: Option<u64>, content_hash: Option<String>) -> Result<FileWriter, ModuleDataError> { decode_file_write(self.data.call(DataOperationV1::FileWriteOpen { file_id: file_id.into(), expected_sequence, content_length, content_hash })?) }\n");
        source.push_str("    pub fn commit_file_write(&mut self, stream_handle: u32) -> Result<DataResultV1, ModuleDataError> { self.data.call(DataOperationV1::FileWriteCommit { stream_handle }) }\n");
        source.push_str("    pub fn abort_file_stream(&mut self, stream_handle: u32) -> Result<DataResultV1, ModuleDataError> { self.data.call(DataOperationV1::FileStreamAbort { stream_handle }) }\n");
    }
    source.push_str("}\n\n");
}

#[cfg(test)]
mod tests;
